"""commercial_erp_stage2_claims_settlements

Revision ID: 0dcbe421ba67
Revises: 4a552571f8e1
Create Date: 2026-09-02 09:50:52.237774+09:00

상용 ERP 확장(2단계) 스키마 변경만 담는다: 클레임(취소/반품/교환) 채널 claim ID/원본상태/
수량/반송비/귀책 필드 및 unmatched 보관 테이블, 정산 회차 유형/상세 매출유형·인식일자,
정산 불일치(discrepancy) 테이블.

--noqa 참고: autogenerate가 이번 스키마와 무관한 기존 드리프트(orders.assignee_id/
confirmed_by, order_items.channel_product_id의 미명명 FK 누락, product_options/
product_unmatched_items/products 일부 컬럼 길이 차이)도 함께 잡아냈으나, 이번 커밋
범위(2단계 클레임/정산) 밖이므로 이 마이그레이션에는 포함하지 않고 수동으로 제외했다.

다운그레이드 데이터 손실 주의: downgrade()는 이 마이그레이션이 추가한 컬럼/테이블을
그대로 drop한다. upgrade() 이후 실제로 채널 claim ID/원본상태/반송비/귀책, 정산
회차유형/상세 매출유형·인식일자를 채운 행이 있거나 claim_unmatched_items/
settlement_discrepancies에 행이 쌓인 상태에서 downgrade하면 그 값들은 전부
유실된다(기존에 있던 취소/반품/교환/정산 행 자체나 그 이전부터 있던 컬럼값은
유실되지 않음 - 격리 PostgreSQL에서 기존 샘플 데이터로 upgrade/downgrade 왕복
검증 완료). 즉 downgrade는 "2단계에서 추가된 데이터"에 한해 손실을 유발하며,
운영에서 downgrade가 필요한 상황이면 이 손실을 감수할지 사전에 확인해야 한다.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcbe421ba67'
down_revision: Union[str, None] = '4a552571f8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_unmatched_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('platform_claim_id', sa.String(length=64), nullable=True),
    sa.Column('platform_order_no', sa.String(length=100), nullable=False),
    sa.Column('raw_status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_claim_unmatched_key', 'claim_unmatched_items', ['platform_id', 'claim_type', 'platform_claim_id', 'platform_order_no'], unique=True)
    op.create_table('settlement_discrepancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('diff_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('detail_summary', sa.String(length=500), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settlement_discrepancies_platform', 'settlement_discrepancies', ['platform_id', 'resolved_at'], unique=False)
    op.add_column('cancellations', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.add_column('cancellations', sa.Column('platform_claim_id', sa.String(length=64), nullable=True))
    op.add_column('cancellations', sa.Column('raw_status', sa.String(length=50), nullable=True))
    op.add_column('cancellations', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('cancellations', sa.Column('shipping_fee', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('cancellations', sa.Column('fault_type', sa.String(length=20), nullable=True))
    op.create_index('uq_cancellation_order_claim_id', 'cancellations', ['order_id', 'platform_claim_id'], unique=True)
    # SQLite는 ALTER TABLE로 제약을 추가할 수 없어(batch mode 필요) 이 FK만 batch로 감쌌다.
    with op.batch_alter_table('cancellations') as batch_op:
        batch_op.create_foreign_key(
            'fk_cancellations_order_item_id_order_items', 'order_items', ['order_item_id'], ['id']
        )
    op.add_column('exchanges', sa.Column('platform_claim_id', sa.String(length=64), nullable=True))
    op.add_column('exchanges', sa.Column('raw_status', sa.String(length=50), nullable=True))
    op.add_column('exchanges', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('exchanges', sa.Column('shipping_fee', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('exchanges', sa.Column('fault_type', sa.String(length=20), nullable=True))
    op.create_index('uq_exchange_order_claim_id', 'exchanges', ['order_id', 'platform_claim_id'], unique=True)
    op.add_column('returns', sa.Column('platform_claim_id', sa.String(length=64), nullable=True))
    op.add_column('returns', sa.Column('raw_status', sa.String(length=50), nullable=True))
    op.add_column('returns', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('returns', sa.Column('shipping_fee', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('returns', sa.Column('fault_type', sa.String(length=20), nullable=True))
    op.create_index('uq_return_order_claim_id', 'returns', ['order_id', 'platform_claim_id'], unique=True)
    op.add_column('settlement_details', sa.Column('sale_type', sa.String(length=10), nullable=True))
    op.add_column('settlement_details', sa.Column('recognition_date', sa.Date(), nullable=True))
    op.add_column('settlements', sa.Column('settlement_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'settlement_type')
    op.drop_column('settlement_details', 'recognition_date')
    op.drop_column('settlement_details', 'sale_type')
    op.drop_index('uq_return_order_claim_id', table_name='returns')
    op.drop_column('returns', 'fault_type')
    op.drop_column('returns', 'shipping_fee')
    op.drop_column('returns', 'quantity')
    op.drop_column('returns', 'raw_status')
    op.drop_column('returns', 'platform_claim_id')
    op.drop_index('uq_exchange_order_claim_id', table_name='exchanges')
    op.drop_column('exchanges', 'fault_type')
    op.drop_column('exchanges', 'shipping_fee')
    op.drop_column('exchanges', 'quantity')
    op.drop_column('exchanges', 'raw_status')
    op.drop_column('exchanges', 'platform_claim_id')
    with op.batch_alter_table('cancellations') as batch_op:
        batch_op.drop_constraint('fk_cancellations_order_item_id_order_items', type_='foreignkey')
    op.drop_index('uq_cancellation_order_claim_id', table_name='cancellations')
    op.drop_column('cancellations', 'fault_type')
    op.drop_column('cancellations', 'shipping_fee')
    op.drop_column('cancellations', 'quantity')
    op.drop_column('cancellations', 'raw_status')
    op.drop_column('cancellations', 'platform_claim_id')
    op.drop_column('cancellations', 'order_item_id')
    op.drop_index('idx_settlement_discrepancies_platform', table_name='settlement_discrepancies')
    op.drop_table('settlement_discrepancies')
    op.drop_index('uq_claim_unmatched_key', table_name='claim_unmatched_items')
    op.drop_table('claim_unmatched_items')
    # ### end Alembic commands ###
