"""widen_external_command_error_code

Revision ID: 54ea89dcc4c0
Revises: 8fbfdc2a67b0
Create Date: 2026-09-03 16:30:32.625068+09:00

external_commands.error_code를 VARCHAR(50) -> VARCHAR(500)로 넓힌다 -
서비스 계층(product_sync_dispatch_service/product_publish_service)의
_describe_exception()이 capability/reason_code가 없는 예외(특히 ValueError의
"필수 항목이 비어 있습니다: ..." 같은 항목별 검증 메시지)를 클래스명 하나로
뭉뚱그리지 않고 그대로 저장하기 위함이다.

⚠️ downgrade 참고(격리 PostgreSQL에서 확인, 2026-09): 넓히기(upgrade)는 항상
안전하다(기존 값 보존). 반대로 좁히기(downgrade)는, 이미 저장된 error_code 값 중
하나라도 50자를 넘으면 PostgreSQL이 psycopg.errors.StringDataRightTruncation을
던지며 downgrade 자체가 실패한다(자동으로 잘라내지 않는다 - 조용한 데이터 손실이
아니라 명시적 실패). 이 downgrade를 실제로 실행해야 한다면, 먼저 50자를 넘는
기존 error_code 값을 운영자가 직접 확인하고 처리 방침을 정한 뒤 진행해야 한다.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ea89dcc4c0'
down_revision: Union[str, None] = '8fbfdc2a67b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_commands', 'error_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_commands', 'error_code',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
