"""product_publish_stage3_bundle2

Revision ID: 8fbfdc2a67b0
Revises: c8d0a24044e4
Create Date: 2026-09-03 10:39:56.181708+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbfdc2a67b0'
down_revision: Union[str, None] = 'c8d0a24044e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_publish_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_option_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('image_urls_json', sa.Text(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('channel_fields_json', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('pending_platform_product_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_option_id', 'platform_id', name='uq_product_publish_draft')
    )
    op.create_table('product_publish_command_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['external_commands.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['product_publish_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_product_publish_command_detail', 'product_publish_command_details', ['command_id'], unique=True)
    op.add_column('product_sync_command_details', sa.Column('target_name', sa.String(length=200), nullable=True))
    op.add_column('product_sync_command_details', sa.Column('target_sale_price', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('product_sync_command_details', sa.Column('target_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sync_command_details', 'target_description')
    op.drop_column('product_sync_command_details', 'target_sale_price')
    op.drop_column('product_sync_command_details', 'target_name')
    op.drop_index('uq_product_publish_command_detail', table_name='product_publish_command_details')
    op.drop_table('product_publish_command_details')
    op.drop_table('product_publish_drafts')
    # ### end Alembic commands ###
